name: CI
on:
  release:
    types: [ published  ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get jar
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "ClassCompanion/discord-bot"
          latest: true
          fileName: "classcompanion-discord-bot.jar"
          out-file-path: ""
          token: ""
      - name: Get release tag
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: ls
        run: ls -la
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TAG_NAME: ${{ steps.get_release.outputs.tag_name }}
          BUILDX: "true"