name: CI
on:
  release:
    types: [ published  ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: |
          ls -la
          pwd

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          repository: ClassCompanion/discord-bot

      - name: ls
        run: |
          ls -la
          pwd

      - name: get jar
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "ClassCompanion/discord-bot"
          latest: true
          fileName: "classcompanion-discord-bot.jar"
          out-file-path: "tobuild/"
          token: ""

      - name: ls
        run: |
          ls -la
          pwd

      - name: Get release tag
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: copy Dockerfile
        uses: canastro/copy-file-action@master
        with:
          source: "Dockerfile"
          target: "tobuild/Dockerfile"

      - name: ls
        run: |
          ls -la
          pwd

      - name: Docker Build and Push
        uses: opspresso/action-docker@v0.3.9
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "classcompanion/discord-bot"
          TAG_NAME: ${{ steps.get_release.outputs.tag_name }}
          BUILD_PATH: "tobuild/"
          BUILDX: "true"
